apiVersion: apps/v1
kind: Deployment
metadata:
  name: girhealthcheck
  labels:
    app: girhealthcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: girhealthcheck
  template:
    metadata:
      labels:
        app: girhealthcheck
    spec:
      containers:
      - name: girhealthcheck
        image: johnebaird/girhealthcheck:latest
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: RWS_HOSTS
          value: "http://192.168.45.81:8080"
        - name: RWS_USER
          value: "jbaird"
        - name: RWS_PASS
          value: "iihbdidj"
        - name: ES_HOSTS
          value: "http://192.168.45.81:9200,http://192.168.45.83:9200"
        - name: WEBDAV_HOSTS
          value: "http://192.168.45.80"
        - name: WEBDAV_USER
          value: "webdav"
        - name: WEBDAV_PASS
          value: "webdav"
        - name: RPS_HOSTS
          value: "http://192.168.45.81:8889"
        - name: RCS_HOSTS
          value: "http://192.168.45.81:8008"


