apiVersion: apps/v1
kind: Deployment
metadata:
  name: girhealthcheck
  labels:
    app: girhealthcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: girhealthcheck
  template:
    metadata:
      labels:
        app: girhealthcheck
    spec:
      containers:
      - name: girhealthcheck
        image: johnebaird/girhealthcheck:latest
        env:
        - name: PYTHONUNBUFFERED
          value: "0"