apiVersion: apps/v1
kind: Deployment
metadata:
  name: girhealthcheck
  labels:
    app: girhealthcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: girhealthcheck
  template:
    metadata:
      labels:
        app: girhealthcheck
    spec:
      containers:
      - name: girhealthcheck
        image: johnebaird/girhealthcheck:latest
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: RWS_HOSTS
          valueFrom:
            configMapKeyRef:
              name: girhealthcheck-conf
              key: rws_hosts
        - name: RWS_USER
          valueFrom:
            secretKeyRef:
              name: girhealthcheck-secret
              key: rws_user
        - name: RWS_PASS
          valueFrom:
            secretKeyRef:
              name: girhealthcheck-secret
              key: rws_pass
        - name: ES_HOSTS
          valueFrom:
            configMapKeyRef:
              name: girhealthcheck-conf
              key: es_hosts
        - name: WEBDAV_HOSTS
          valueFrom:
            configMapKeyRef:
              name: girhealthcheck-conf
              key: webdav_hosts
        - name: WEBDAV_USER
          valueFrom:
            secretKeyRef:
              name: girhealthcheck-secret
              key: webdav_user
        - name: WEBDAV_PASS
          valueFrom:
            secretKeyRef:
              name: girhealthcheck-secret
              key: webdav_pass
        - name: RPS_HOSTS
          valueFrom:
            configMapKeyRef:
              name: girhealthcheck-conf
              key: rps_hosts
        - name: RCS_HOSTS
          valueFrom:
            configMapKeyRef:
              name: girhealthcheck-conf
              key: rcs_hosts


