apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: pvc001
spec:
        storageClassName: slow 
        accessModes: 
          - ReadWriteOnce
        resources:
                requests:
                        storage: 500M
