apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
        rws_user: {{ .Values.rws_user | b64enc }}
        rws_pass: {{ .Values.rws_pass | b64enc }} 
        webdav_user: {{ .Values.webdav_user | b64enc }}
        webdav_pass: {{ .Values.webdav_pass | b64enc }}

